# Generated by Django 4.0.6 on 2022-07-22 11:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0002_games_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
